# Generated by Django 5.1.1 on 2024-09-09 06:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kindergarten',
            fields=[
                ('kindergarten_id', models.AutoField(primary_key=True, serialize=False)),
                ('postal_code', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=128)),
                ('policy', models.TextField()),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('shared_sheet', models.TextField()),
                ('date', models.DateField()),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_app.kindergarten')),
            ],
        ),
        migrations.CreateModel(
            name='Caregiver',
            fields=[
                ('caregiver_id', models.AutoField(primary_key=True, serialize=False)),
                ('grade', models.IntegerField()),
                ('name', models.CharField(max_length=100)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_app.kindergarten')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('student_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('grade', models.IntegerField()),
                ('birth_date', models.DateField()),
                ('allergy_info', models.TextField(blank=True, null=True)),
                ('additional_info', models.TextField(blank=True, null=True)),
                ('kindergarten', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_app.kindergarten')),
            ],
        ),
        migrations.CreateModel(
            name='StudentJournal',
            fields=[
                ('journal_id', models.AutoField(primary_key=True, serialize=False)),
                ('student_info', models.TextField()),
                ('date', models.DateField()),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='log_app.student')),
            ],
        ),
    ]
