# Generated by Django 5.1.1 on 2024-09-09 08:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('log_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='journal',
            name='grade',
        ),
        migrations.RemoveField(
            model_name='student',
            name='grade',
        ),
        migrations.AddField(
            model_name='journal',
            name='caregiver',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='log_app.caregiver'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='caregiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='log_app.caregiver'),
        ),
    ]
